### ISSUE TITLE
BUG: UTXO chains unable to send after first UTXO from wallet

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#667]
**Describe the bug**
It is impossible to send further txs after the first ever UTXO was sent.
Possible due to some payload creation error.

**To Reproduce**
1. send first tx on UTXO chain
2. send second tx on UTXO chain
3. See error

**Expected behavior**
able to send UTXOs consistently

v12

**Comment by johnnyluo** [comment]
I believe this is because previous build , we cache UTXO balance for 5 minutes , so immediately after sending out one , even it committed to block , the UTXO balance will not reflected in the app , thus the second keysign , it might not work
If wait for a little longer , and refresh the balance , it should be fine
Now we already removed the cache in #692  , this should be fixed

**Comment by realpaaao** [comment]
still reproducable. @yvebe didn't you also already implement some fiy last week?

**Comment by johnnyluo** [comment]
Fixed , closing
